// <auto-generated />
using System;
using FISIOSPORT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FISIOSPORT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921151427_AgregarCatalogoEjerciciosYAsignacionPorCita")]
    partial class AgregarCatalogoEjerciciosYAsignacionPorCita
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FISIOSPORT.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("FisioterapeutaId")
                        .HasColumnType("integer");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("SesionTratamientoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapeutaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("SesionTratamientoId")
                        .IsUnique();

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("FISIOSPORT.Models.ConsultaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Antecedentes")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("CicatrizQuirurgica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiagnosticoMedico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiagnosticoRehabilitacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EscalaDolor")
                        .HasColumnType("integer");

                    b.Property<string>("EspasmosContractura")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FisioterapeutaId")
                        .HasColumnType("integer");

                    b.Property<string>("LenguajeOrientacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Marcha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Movilidad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("OtrosHallazgos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Reflejos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Sensibilidad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SignosVitales")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TratamientosPrevios")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapeutaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("ConsultasClinicas");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("FasePaciente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ObjetivoTerapeutico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RegionAnatomica")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoContraccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FasePaciente");

                    b.HasIndex("Nombre");

                    b.HasIndex("ObjetivoTerapeutico");

                    b.HasIndex("RegionAnatomica");

                    b.HasIndex("TipoContraccion");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("FISIOSPORT.Models.EjercicioAsignado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CitaId")
                        .HasColumnType("integer");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("InstruccionesPersonalizadas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ProgramaRehabilitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("ProgramaRehabilitacionId");

                    b.ToTable("EjerciciosAsignados");
                });

            modelBuilder.Entity("FISIOSPORT.Models.EvolucionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FisioterapeutaId")
                        .HasColumnType("integer");

                    b.Property<string>("Informe")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("ProgramaRehabilitacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapeutaId");

                    b.HasIndex("ProgramaRehabilitacionId");

                    b.ToTable("EvolucionesDiarias");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Fisioterapeuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroColegiado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Fisioterapeutas");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactoEmergencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Escolaridad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Estatura")
                        .HasColumnType("numeric");

                    b.Property<string>("Etnia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Talla")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("FISIOSPORT.Models.ProgramaRehabilitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FisioterapeutaId")
                        .HasColumnType("integer");

                    b.Property<string>("ObjetivoGeneral")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("SesionesCompletadas")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSesiones")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapeutaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("ProgramasRehabilitacion");
                });

            modelBuilder.Entity("FISIOSPORT.Models.RegistroEjercicioPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completado")
                        .HasColumnType("boolean");

                    b.Property<int>("EjercicioAsignadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("EjercicioAsignadoId", "PacienteId", "Fecha")
                        .IsUnique();

                    b.ToTable("RegistrosEjerciciosPaciente");
                });

            modelBuilder.Entity("FISIOSPORT.Models.SesionTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumeroSesion")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TrabajoPlanificado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TratamientoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId", "NumeroSesion")
                        .IsUnique();

                    b.ToTable("SesionesTratamiento");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("FisioterapeutaId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSesiones")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapeutaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Cita", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Fisioterapeuta", "Fisioterapeuta")
                        .WithMany("Citas")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.SesionTratamiento", "SesionTratamiento")
                        .WithOne("Cita")
                        .HasForeignKey("FISIOSPORT.Models.Cita", "SesionTratamientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");

                    b.Navigation("SesionTratamiento");
                });

            modelBuilder.Entity("FISIOSPORT.Models.ConsultaClinica", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Fisioterapeuta", "Fisioterapeuta")
                        .WithMany("ConsultasClinicas")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.Paciente", "Paciente")
                        .WithMany("ConsultasClinicas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("FISIOSPORT.Models.EjercicioAsignado", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Cita", "Cita")
                        .WithMany("EjerciciosAsignados")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FISIOSPORT.Models.Ejercicio", "Ejercicio")
                        .WithMany("Asignaciones")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.ProgramaRehabilitacion", "ProgramaRehabilitacion")
                        .WithMany("EjerciciosAsignados")
                        .HasForeignKey("ProgramaRehabilitacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cita");

                    b.Navigation("Ejercicio");

                    b.Navigation("ProgramaRehabilitacion");
                });

            modelBuilder.Entity("FISIOSPORT.Models.EvolucionDiaria", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Fisioterapeuta", "Fisioterapeuta")
                        .WithMany("Evoluciones")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.ProgramaRehabilitacion", "ProgramaRehabilitacion")
                        .WithMany("Evoluciones")
                        .HasForeignKey("ProgramaRehabilitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("ProgramaRehabilitacion");
                });

            modelBuilder.Entity("FISIOSPORT.Models.ProgramaRehabilitacion", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Fisioterapeuta", "Fisioterapeuta")
                        .WithMany("ProgramasRehabilitacion")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.Paciente", "Paciente")
                        .WithMany("ProgramasRehabilitacion")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("FISIOSPORT.Models.RegistroEjercicioPaciente", b =>
                {
                    b.HasOne("FISIOSPORT.Models.EjercicioAsignado", "EjercicioAsignado")
                        .WithMany()
                        .HasForeignKey("EjercicioAsignadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.Paciente", "Paciente")
                        .WithMany("RegistrosEjercicios")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EjercicioAsignado");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("FISIOSPORT.Models.SesionTratamiento", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Tratamiento", "Tratamiento")
                        .WithMany("Sesiones")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Tratamiento", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Fisioterapeuta", "Fisioterapeuta")
                        .WithMany("Tratamientos")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.Paciente", "Paciente")
                        .WithMany("Tratamientos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Cita", b =>
                {
                    b.Navigation("EjerciciosAsignados");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Ejercicio", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Fisioterapeuta", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("ConsultasClinicas");

                    b.Navigation("Evoluciones");

                    b.Navigation("ProgramasRehabilitacion");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("ConsultasClinicas");

                    b.Navigation("ProgramasRehabilitacion");

                    b.Navigation("RegistrosEjercicios");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("FISIOSPORT.Models.ProgramaRehabilitacion", b =>
                {
                    b.Navigation("EjerciciosAsignados");

                    b.Navigation("Evoluciones");
                });

            modelBuilder.Entity("FISIOSPORT.Models.SesionTratamiento", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Tratamiento", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
