// <auto-generated />
using System;
using FISIOSPORT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FISIOSPORT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917164721_AgregarTratamientosYSesiones")]
    partial class AgregarTratamientosYSesiones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FISIOSPORT.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("FisioterapeutaId")
                        .HasColumnType("integer");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("SesionTratamientoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapeutaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("SesionTratamientoId")
                        .IsUnique();

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Fisioterapeuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroColegiado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Fisioterapeutas");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactoEmergencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("FISIOSPORT.Models.SesionTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumeroSesion")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TrabajoPlanificado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TratamientoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId", "NumeroSesion")
                        .IsUnique();

                    b.ToTable("SesionesTratamiento");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("FisioterapeutaId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSesiones")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FisioterapeutaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Cita", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Fisioterapeuta", "Fisioterapeuta")
                        .WithMany("Citas")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.SesionTratamiento", "SesionTratamiento")
                        .WithOne("Cita")
                        .HasForeignKey("FISIOSPORT.Models.Cita", "SesionTratamientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");

                    b.Navigation("SesionTratamiento");
                });

            modelBuilder.Entity("FISIOSPORT.Models.SesionTratamiento", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Tratamiento", "Tratamiento")
                        .WithMany("Sesiones")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Tratamiento", b =>
                {
                    b.HasOne("FISIOSPORT.Models.Fisioterapeuta", "Fisioterapeuta")
                        .WithMany("Tratamientos")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FISIOSPORT.Models.Paciente", "Paciente")
                        .WithMany("Tratamientos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Fisioterapeuta", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("FISIOSPORT.Models.SesionTratamiento", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("FISIOSPORT.Models.Tratamiento", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
